from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QMessageBox

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 472)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.formLayout = QtWidgets.QFormLayout(self.centralwidget)
        self.formLayout.setObjectName("formLayout")

        # Container esquerdo
        self.containerEsquerdo = QtWidgets.QFrame(self.centralwidget)
        self.containerEsquerdo.setMaximumSize(QtCore.QSize(200, 16777215))
        self.containerEsquerdo.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.containerEsquerdo.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.containerEsquerdo.setObjectName("containerEsquerdo")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.containerEsquerdo)
        self.verticalLayout_4.setObjectName("verticalLayout_4")

        # Frame 2
        self.frame_2 = QtWidgets.QFrame(self.containerEsquerdo)
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.verticalLayout_4.addWidget(self.frame_2)

        # Frame
        self.frame = QtWidgets.QFrame(self.containerEsquerdo)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.toolBox = QtWidgets.QToolBox(self.frame)
        self.toolBox.setObjectName("toolBox")

        # Page
        self.page = QtWidgets.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 115, 269))
        self.page.setObjectName("page")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.pushButton_2 = QtWidgets.QPushButton(self.page)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_6.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.page)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout_6.addWidget(self.pushButton_3)
        self.pushButton_4 = QtWidgets.QPushButton(self.page)
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout_6.addWidget(self.pushButton_4)
        self.pushButton_5 = QtWidgets.QPushButton(self.page)
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout_6.addWidget(self.pushButton_5)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_6.addItem(spacerItem)
        self.toolBox.addItem(self.page, "")

        # Page 2
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setGeometry(QtCore.QRect(0, 0, 147, 269))
        self.page_2.setObjectName("page_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.page_2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.page_2)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.toolBox.addItem(self.page_2, "")
        self.verticalLayout_5.addWidget(self.toolBox)
        self.verticalLayout_4.addWidget(self.frame)
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.containerEsquerdo)

        # Container direito
        self.containerDireito = QtWidgets.QFrame(self.centralwidget)
        self.containerDireito.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.containerDireito.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.containerDireito.setObjectName("containerDireito")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.containerDireito)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frameCima = QtWidgets.QFrame(self.containerDireito)
        self.frameCima.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frameCima.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frameCima.setObjectName("frameCima")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frameCima)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.frameCima)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.verticalLayout.addWidget(self.frameCima)
        self.mainFrame = QtWidgets.QFrame(self.containerDireito)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mainFrame.sizePolicy().hasHeightForWidth())
        self.mainFrame.setSizePolicy(sizePolicy)
        self.mainFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.mainFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.mainFrame.setObjectName("mainFrame")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.mainFrame)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.Paginas = QtWidgets.QStackedWidget(self.mainFrame)
        self.Paginas.setObjectName("Paginas")

        # Home Page
        self.HomePg = QtWidgets.QWidget()
        self.HomePg.setObjectName("HomePg")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.HomePg)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.frame_8 = QtWidgets.QFrame(self.HomePg)
        self.frame_8.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_8.setObjectName("frame_8")
        self.label_11 = QtWidgets.QLabel(self.frame_8)
        self.label_11.setGeometry(QtCore.QRect(180, -10, 171, 145))
        self.label_11.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.label_11.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.label_11.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.label_11.setText("")
        self.label_11.setPixmap(QtGui.QPixmap("imgs/aplicativo-web.png"))
        self.label_11.setScaledContents(True)
        self.label_11.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_11.setWordWrap(False)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_20.addWidget(self.frame_8)
        self.frame_7 = QtWidgets.QFrame(self.HomePg)
        self.frame_7.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.frame_7)
        self.lineEdit_7.setText("")
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.verticalLayout_19.addWidget(self.lineEdit_7)
        self.lineEdit_8 = QtWidgets.QLineEdit(self.frame_7)
        self.lineEdit_8.setText("")
        self.lineEdit_8.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.lineEdit_8.setPlaceholderText("Senha")
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.verticalLayout_19.addWidget(self.lineEdit_8)
        self.pushButton_17 = QtWidgets.QPushButton(self.frame_7)
        self.pushButton_17.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton_17.setObjectName("pushButton_17")
        self.verticalLayout_19.addWidget(self.pushButton_17)
        self.verticalLayout_20.addWidget(self.frame_7)
        self.Paginas.addWidget(self.HomePg)

        # Cadastro Page
        self.CadastroPg = QtWidgets.QWidget()
        self.CadastroPg.setObjectName("CadastroPg")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.CadastroPg)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.tabWidget = QtWidgets.QTabWidget(self.CadastroPg)
        self.tabWidget.setObjectName("tabWidget")

        # Tab
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout = QtWidgets.QGridLayout(self.tab)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_3 = QtWidgets.QFrame(self.tab)
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.label_5 = QtWidgets.QLabel(self.frame_3)
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_5.setStyleSheet("background: rgb(255,255,255)")
        self.label_5.setObjectName("label_5")
        self.verticalLayout_14.addWidget(self.label_5)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_3.setText("")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.verticalLayout_10.addWidget(self.lineEdit_3)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout_10.addWidget(self.lineEdit_2)
        self.lineEdit = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_10.addWidget(self.lineEdit)
        self.verticalLayout_14.addLayout(self.verticalLayout_10)
        self.pushButton_12 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_12.setObjectName("pushButton_12")
        self.verticalLayout_14.addWidget(self.pushButton_12)
        self.gridLayout.addWidget(self.frame_3, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")

        # Tab 2
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_6 = QtWidgets.QLabel(self.tab_2)
        self.label_6.setMaximumSize(QtCore.QSize(16777215, 39))
        self.label_6.setStyleSheet("background: rgb(255,255,255)")
        self.label_6.setObjectName("label_6")
        self.verticalLayout_13.addWidget(self.label_6)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.tableWidget = QtWidgets.QTableWidget(self.tab_2)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        self.horizontalLayout_4.addWidget(self.tableWidget)
        self.frame_4 = QtWidgets.QFrame(self.tab_2)
        self.frame_4.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.pushButton_9 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_9.setObjectName("pushButton_9")
        self.verticalLayout_12.addWidget(self.pushButton_9)
        self.pushButton_10 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_10.setObjectName("pushButton_10")
        self.verticalLayout_12.addWidget(self.pushButton_10)
        self.pushButton_11 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_11.setObjectName("pushButton_11")
        self.verticalLayout_12.addWidget(self.pushButton_11)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_12.addItem(spacerItem1)
        self.horizontalLayout_4.addWidget(self.frame_4)
        self.verticalLayout_13.addLayout(self.horizontalLayout_4)
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout_8.addWidget(self.tabWidget)
        self.Paginas.addWidget(self.CadastroPg)

        # Contatos Page
        self.ContatosPg = QtWidgets.QWidget()
        self.ContatosPg.setObjectName("ContatosPg")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.ContatosPg)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_7 = QtWidgets.QLabel(self.ContatosPg)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_11.addWidget(self.label_7)
        self.Paginas.addWidget(self.ContatosPg)

        # Equipamentos Page
        self.EquipamentosPg = QtWidgets.QWidget()
        self.EquipamentosPg.setObjectName("EquipamentosPg")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.EquipamentosPg)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.EquipamentosPg)
        self.tabWidget_2.setObjectName("tabWidget_2")

        # Tab 3
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame_5 = QtWidgets.QFrame(self.tab_3)
        self.frame_5.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.label_8 = QtWidgets.QLabel(self.frame_5)
        self.label_8.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_8.setStyleSheet("background: rgb(255,255,255)")
        self.label_8.setObjectName("label_8")
        self.verticalLayout_15.addWidget(self.label_8)
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.frame_5)
        self.lineEdit_4.setText("")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.verticalLayout_16.addWidget(self.lineEdit_4)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.frame_5)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.verticalLayout_16.addWidget(self.lineEdit_5)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.frame_5)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.verticalLayout_16.addWidget(self.lineEdit_6)
        self.verticalLayout_15.addLayout(self.verticalLayout_16)
        self.pushButton_13 = QtWidgets.QPushButton(self.frame_5)
        self.pushButton_13.setObjectName("pushButton_13")
        self.verticalLayout_15.addWidget(self.pushButton_13)
        self.gridLayout_2.addWidget(self.frame_5, 0, 0, 1, 1)
        self.tabWidget_2.addTab(self.tab_3, "")

        # Tab 4
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.tab_4)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.label_9 = QtWidgets.QLabel(self.tab_4)
        self.label_9.setMaximumSize(QtCore.QSize(16777215, 39))
        self.label_9.setStyleSheet("background: rgb(255,255,255)")
        self.label_9.setObjectName("label_9")
        self.verticalLayout_17.addWidget(self.label_9)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.tab_4)
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(3)
        self.tableWidget_2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        self.horizontalLayout_5.addWidget(self.tableWidget_2)
        self.frame_6 = QtWidgets.QFrame(self.tab_4)
        self.frame_6.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.pushButton_14 = QtWidgets.QPushButton(self.frame_6)
        self.pushButton_14.setObjectName("pushButton_14")
        self.verticalLayout_18.addWidget(self.pushButton_14)
        self.pushButton_15 = QtWidgets.QPushButton(self.frame_6)
        self.pushButton_15.setObjectName("pushButton_15")
        self.verticalLayout_18.addWidget(self.pushButton_15)
        self.pushButton_16 = QtWidgets.QPushButton(self.frame_6)
        self.pushButton_16.setObjectName("pushButton_16")
        self.verticalLayout_18.addWidget(self.pushButton_16)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_18.addItem(spacerItem2)
        self.horizontalLayout_5.addWidget(self.frame_6)
        self.verticalLayout_17.addLayout(self.horizontalLayout_5)
        self.tabWidget_2.addTab(self.tab_4, "")
        self.verticalLayout_9.addWidget(self.tabWidget_2)
        self.Paginas.addWidget(self.EquipamentosPg)

        self.verticalLayout_7.addWidget(self.Paginas)
        self.verticalLayout.addWidget(self.mainFrame)

        # Frame Baixo
        self.frameBaixo = QtWidgets.QFrame(self.containerDireito)
        self.frameBaixo.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frameBaixo.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frameBaixo.setObjectName("frameBaixo")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frameBaixo)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.frameBaixo)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.verticalLayout.addWidget(self.frameBaixo)
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.containerDireito)

        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.toolBox.setCurrentIndex(0)
        self.Paginas.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        # Connect buttons to their respective functions
        self.pushButton_17.clicked.connect(self.login)
        self.pushButton_2.clicked.connect(lambda: self.Paginas.setCurrentIndex(0))
        self.pushButton_3.clicked.connect(lambda: self.Paginas.setCurrentIndex(1))
        self.pushButton_4.clicked.connect(lambda: self.Paginas.setCurrentIndex(2))
        self.pushButton_5.clicked.connect(lambda: self.Paginas.setCurrentIndex(3))

        # Initialize user data
        self.users = {"admin": "password"}  # Simple user database

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "Academia VivaMais"))
        self.pushButton_2.setText(_translate("MainWindow", "Home"))
        self.pushButton_3.setText(_translate("MainWindow", "Cadastro"))
        self.pushButton_4.setText(_translate("MainWindow", "Contatos"))
        self.pushButton_5.setText(_translate("MainWindow", "Equipamentos"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page), _translate("MainWindow", "Page 1"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:6pt; font-weight:600; color:#c6c7ff;\">Academia Viva+</span></p><p align=\"center\"><span style=\" font-size:6pt; font-weight:600; color:#c6c7ff;\">Status:</span><span style=\" font-size:6pt; color:#c6c7ff;\"> ativa</span></p><p align=\"center\"><span style=\" font-size:6pt; font-weight:600; color:#c6c7ff;\">Telefone:</span><span style=\" font-size:6pt; color:#c6c7ff;\"> (99)99999-9999</span></p><p align=\"center\"><span style=\" font-size:6pt; font-weight:600; color:#c6c7ff;\">Email:</span><span style=\" font-size:6pt; color:#c6c7ff;\"> vivamais@gmail.com</span></p></body></html>"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_2), _translate("MainWindow", "Page 2"))
        self.label.setText(_translate("MainWindow", "Academia VivaMais"))
        self.lineEdit_7.setPlaceholderText(_translate("MainWindow", "User"))
        self.pushButton_17.setText(_translate("MainWindow", "Entrar"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600; color:#ceb5ff;\">Cadastrar alunos | Academia VivaMais</span></p></body></html>"))
        self.lineEdit_3.setPlaceholderText(_translate("MainWindow", "CPF"))
        self.lineEdit_2.setPlaceholderText(_translate("MainWindow", "NOME"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "MATRÍCULA"))
        self.pushButton_12.setText(_translate("MainWindow", "Adicionar"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Cadastro"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600; color:#ceb5ff;\">Alunos | Academia VivaMais</span></p></body></html>"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "MATRÍCULA"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "NOME"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "CPF"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "PAGAMENTO"))
        self.pushButton_9.setText(_translate("MainWindow", "Gerar Excel"))
        self.pushButton_10.setText(_translate("MainWindow", "Adicionar"))
        self.pushButton_11.setText(_translate("MainWindow", "Excluir"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Alunos"))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; font-weight:600;\">vivamais@email.com</span></p><p align=\"center\"><span style=\" font-size:18pt; font-weight:600;\">CNPJ XX.XXX.XXX/0001-XX</span></p><p align=\"center\"><span style=\" font-size:18pt; font-weight:600;\">Telefone (99)9999-9999</span></p><p align=\"center\"><span style=\" font-size:18pt; font-weight:600;\">Whatsapp (99)99999-9999</span></p></body></html>"))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600; color:#ceb5ff;\">Cadastrar equipamentos | Academia VivaMais</span></p></body></html>"))
        self.lineEdit_4.setPlaceholderText(_translate("MainWindow", "ID"))
        self.lineEdit_5.setPlaceholderText(_translate("MainWindow", "NOME DO EQUIPAMENTO"))
        self.lineEdit_6.setPlaceholderText(_translate("MainWindow", "DATA DE CADASTRO"))
        self.pushButton_13.setText(_translate("MainWindow", "Adicionar"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_3), _translate("MainWindow", "Cadastro"))
        self.label_9.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600; color:#ceb5ff;\">Equipamentos | Academia VivaMais</span></p></body></html>"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "NOME DO EQ."))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "DATA DE REG."))
        self.pushButton_14.setText(_translate("MainWindow", "Gerar Excel"))
        self.pushButton_15.setText(_translate("MainWindow", "Adicionar"))
        self.pushButton_16.setText(_translate("MainWindow", "Excluir"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), _translate("MainWindow", "Equipamentos"))
        self.label_2.setText(_translate("MainWindow", "Academia VivaMais"))

    def login(self):
        username = self.lineEdit_7.text()
        password = self.lineEdit_8.text()
        if username in self.users and self.users[username] == password:
            QMessageBox.information(None, "Login", "Login successful!")
            self.Paginas.setCurrentIndex(0)  # Go to the home page
        else:
            QMessageBox.warning(None, "Login", "Invalid username or password.")

    def register(self):
        dialog = RegisterDialog(self)
        if dialog.exec() == QtWidgets.QDialog.DialogCode.Accepted:
            username, password = dialog.get_credentials()
            if username in self.users:
                QMessageBox.warning(None, "Registro", "Usuário já existe.")
            else:
                self.users[username] = password
                QMessageBox.information(None, "Registro", "Registro bem-sucedido!")

class RegisterDialog(QtWidgets.QDialog):
    def __init__(self, parent=None):
        super().__init__(parent)
        self.setWindowTitle("Registrar")
        self.setFixedSize(300, 150)

        self.layout = QtWidgets.QVBoxLayout()

        self.label_username = QtWidgets.QLabel("Usuário:")
        self.lineEdit_username = QtWidgets.QLineEdit()

        self.label_password = QtWidgets.QLabel("Senha:")
        self.lineEdit_password = QtWidgets.QLineEdit()
        self.lineEdit_password.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)

        self.buttonBox = QtWidgets.QDialogButtonBox()
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Ok | QtWidgets.QDialogButtonBox.StandardButton.Cancel)
        self.buttonBox.accepted.connect(self.accept)
        self.buttonBox.rejected.connect(self.reject)

        self.layout.addWidget(self.label_username)
        self.layout.addWidget(self.lineEdit_username)
        self.layout.addWidget(self.label_password)
        self.layout.addWidget(self.lineEdit_password)
        self.layout.addWidget(self.buttonBox)

        self.setLayout(self.layout)

    def get_credentials(self):
        return self.lineEdit_username.text(), self.lineEdit_password.text()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())